default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: realtor_development
test:
  <<: *default
  database: realtor_test
production:
  <<: *default
  database: realtor_production
  username: realtor
  password: <%= ENV['REALTOR_DATABASE_PASSWORD'] %>
