default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
development:
  <<: *default
  database: realtors_development
test:
  <<: *default
  database: realtors_test
production:
  <<: *default
  database: lystey-production
  username: realtors
  password: <%= ENV['REALTORS_DATABASE_PASSWORD'] %>
  host: lystey-production.c0hit0u0x5jp.us-east-1.rds.amazonaws.com:5432
  port: 5432
