default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: realtors_development
test:
  <<: *default
  database: realtors_test
production:
  <<: *default
  database: realtors_production
  username: realtors
  password: <%= ENV['REALTOR_DATABASE_PASSWORD'] %>
