default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
development:
  <<: *default
  database: realtors_development
test:
  <<: *default
  database: realtors_test
production:
  <<: *default
  database: realtors_production
  username: realtors
  password: <%= ENV['REALTOR_DATABASE_PASSWORD'] %>
  host: realtors-production.c0hit0u0x5jp.us-east-1.rds.amazonaws.com
  port: 5432
